routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'HomeController@index');

Route::get('/pages/detail/{id}', 'PageController@detail')->name('page.detail');
Route::get('/product/detail/{id}', 'ProductController@detail')->name('product.detail');
Route::get('/product/view', 'ProductController@view')->name('product.view');
Route::get('/cart/view', 'CartController@view')->name('cart.view');


Route::resource('orderItem','OrderItemController');//resource route
Route::resource('cart','CartController');//resource route
Route::resource('sliders','SliderController');//resource route
//Route::get('/sliders','SliderController@index');
//Route::get('/sliders.create','SliderController@create');
//Route::get('/slider-detail/{id}','SliderController@show');
Route::resource('category', 'CategoryController');
Route::get('/category/view', 'CategoryController@view')->name('category.view');
Route::resource('product', 'ProductController');
Route::resource('staticblock', 'StaticblockController');
Route::resource('review', 'ReviewController');
Route::resource('picture', 'PictureController');
Route::resource('subscriber', 'SubscriberController');
Route::resource('page', 'PageController');
Route::resource('checkout', 'CheckoutController');
Route::get('/checkout/message', 'CheckoutController@message')->name('checkout.message');
Route::get('orders/{id}/download', 'CheckoutController@download');
//Route::get('/category','CategoryController@index');
//Route::get('/product','ProductController@index');



//////////////////////////////////

Route::get('/', function () {
    return view('welcome');
});
Route::get('/about', function () {
    return view('about');
});
Route::get('/404', function () {
    return view('404');
});
Route::get('/gallery-post', function () {
    return view('gallery-post');
});
///////////////////
Route::get('/gggallery-post', function () {
    return view('gggallery-post');
});
Route::get('/grid', function () {
    return view('grid');
});
Route::get('/listing-with-sidbar', function () {
    return view('listing-with-sidbar');
});
Route::get('/listing-without-sidbar', function () {
    return view('listing-without-sidbar');
});
Route::get('/masonry', function () {
    return view('masonry');
});
Route::get('/standart-post', function () {
    return view('standart-post');
});
Route::get('/text-post', function () {
    return view('text-post');
});
Route::get('/video-post', function () {
    return view('video-post');
});
Route::get('/cart-1', function () {
    return view('cart-1');
});
Route::get('/cart-2', function () {
    return view('cart-2');
});
Route::get('/checkout-1', function () {
    return view('checkout-1');
});
Route::get('/checkout-2', function () {
    return view('checkout-2');
});
Route::get('/coming-soon', function () {
    return view('coming-soon');
});
Route::get('/compare', function () {
    return view('compare');
});
Route::get('/contacts', function () {
    return view('contacts');
});
Route::get('/elements-accordion', function () {
    return view('elements-accordion');
});
Route::get('/elements-banners', function () {
    return view('elements-banners');
});
Route::get('/elements-buttons', function () {
    return view('elements-buttons');
});
Route::get('/elements-icon-box', function () {
    return view('elements-icon-box');
});
Route::get('/elements-maps', function () {
    return view('elements-maps');
});
Route::get('/elements-product', function () {
    return view('elements-product');
});
Route::get('/elements-progress-bar', function () {
    return view('elements-progress-bar');
});
Route::get('/elements-social', function () {
    return view('elements-social');
});
Route::get('/elements-tabs', function () {
    return view('elements-tabs');
});
Route::get('/elements-toggles', function () {
    return view('elements-toggles');
});
Route::get('/elements-typography', function () {
    return view('elements-typography');
});
Route::get('/empty-category', function () {
    return view('empty-category');
});
Route::get('/empty-compare', function () {
    return view('empty-compare');
});
Route::get('/empty-search', function () {
    return view('empty-search');
});
Route::get('/empty-shopping-cart', function () {
    return view('empty-shopping-cart');
});
Route::get('/empty-wishlist', function () {
    return view('empty-wishlist');
});
Route::get('/faq', function () {
    return view('faq');
});
Route::get('/gallery', function () {
    return view('gallery');
});
Route::get('/gallery-3-thumbs', function () {
    return view('gallery-3-thumbs');
});
Route::get('/gallery-4-thumbs', function () {
    return view('gallery-4-thumbs');
});
Route::get('/gallery-masonry', function () {
    return view('gallery-masonry');
});
Route::get('/index', function () {
    return view('index');
});
Route::get('/index-02', function () {
    return view('index-02');
});
Route::get('/index-03', function () {
    return view('index-03');
});
Route::get('/index-04', function () {
    return view('index-04');
});
Route::get('/index-05', function () {
    return view('index-05');
});
Route::get('/index-06', function () {
    return view('index-06');
});
Route::get('/index-07', function () {
    return view('index-07');
});
Route::get('/index-08', function () {
    return view('index-08');
});
Route::get('/index-09', function () {
    return view('index-09');
});
Route::get('/index-10', function () {
    return view('index-10');
});
Route::get('/index-11', function () {
    return view('index-11');
});
Route::get('/index-12', function () {
    return view('index-12');
});
Route::get('/listing', function () {
    return view('listing');
});
Route::get('/listing-big-reviews', function () {
    return view('listing-big-reviews');
});
Route::get('/listing-catalogue', function () {
    return view('listing-catalogue');
});
Route::get('/listing-collections', function () {
    return view('listing-collections');
});
Route::get('/listing-fullwidth', function () {
    return view('listing-fullwidth');
});
Route::get('/listing-right-sidebar', function () {
    return view('listing-right-sidebar');
});
Route::get('/listing-with-custom-html-block', function () {
    return view('listing-with-custom-html-block');
});
Route::get('/listing-without-columns', function () {
    return view('listing-without-columns');
});
Route::get('/listing-with-sidebar', function () {
    return view('listing-with-sidebar');
});
Route::get('/login', function () {
   return view('login');
});


Route::get('/my-account', function () {
    return view('my-account');
});
//Route::get('/product', function () {
   // return view('product');
//});
Route::get('/product-grouped', function () {
    return view('product-grouped');
});
Route::get('/product-on-sale', function () {
    return view('product-on-sale');
});
Route::get('/product-out-of-stock', function () {
    return view('product-out-of-stock');
});

Route::get('/product-simple-variant-1', function () {
    return view('product-simple-variant-1');
});
Route::get('/product-simple-variant-2', function () {
    return view('product-simple-variant-2');
});
Route::get('/product-variable', function () {
    return view('product-variable');

});
Route::get('/register', function () {
    return view('register');
});
//Route::get('/services', function () {
   // return view('services');
//});
//Route::get('/sitemap', function () {
    //return view('sitemap');
//});
//Route::get('/wishlist', function () {
   // return view('wishlist');
//});

Auth::routes();

Route::get('/home','HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Carbon\Carbon;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories    = Category::latest()->paginate(5);
        return view('category.index',compact('categories'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.category');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        $this->validate($request,[
//
//            'title'=>'required',
//            'created_by'=>'required',
//            'updated_by'=>'required',
//
//        ]);

        $categories  = new Category;
        $categories->title = $request->title;
        if ($request->hasFile('image')) {
            $uploadPath = public_path('/uploads/category');
            $extension = $request->image->getClientOriginalExtension();
            $timestamp = str_replace([' ', ':'], '--', Carbon::now()->toDateTimeString());//formatting the name for unique and readable
            $fileName = $timestamp . '.' . $extension;
            $request->image->move($uploadPath, $fileName);
            $categories->image = $fileName;
        }else{
            $categories->image = NULL;
        }
        $categories ->created_by= $request->created_by;
        $categories ->updated_by = $request->updated_by;
        $categories ->save();

        return redirect(route('category.index'))->withMessage('Category Added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category= Category::find($id);
        return view('category.show')->with('category',$category);
    }

    public function view()
    {
        $categories = Category::latest()->paginate(6);
        return view('category.view',compact('categories'));

    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::where('id',$id)->first();
        return view('category.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
//        $this->validate($request,[
//
//            'title'=>'required',
//            'created_by'=>'required',
//            'updated_by'=>'required',
//
//        ]);

        $category = Category::find($id);
        $category->title = $request->title;
        if ($request->hasFile('image')) {
            $uploadPath = public_path('/uploads/category');
            $extension = $request->image->getClientOriginalExtension();
            $timestamp = str_replace([' ', ':'], '--', Carbon::now()->toDateTimeString());//formatting the name for unique and readable
            $fileName = $timestamp . '.' . $extension;
            $request->image->move($uploadPath, $fileName);
            $category->image = $fileName;
        }else{
            $category->image = NULL;
        }
        $category->created_by= $request->created_by;
        $category->updated_by= $request->updated_by;
        $category->save();

        return redirect(route('category.index'))->withMessage('Category Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::where('id',$id)->delete();
        return redirect()->back()->withMessage('Category Deleted Successfully');
    }
}

resources/views/category/edit.blade.php
@extends('layouts/mogo')

@section('main_content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-2">

                    <div class="panel-heading"><h5 style="text-align: center">Category Edit Form</h5></div>

                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('category.update',$category->id) }}" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}
                            <div class="form-group">
                                <label for="title" class="col-md-4 control-label">Title</label>

                                <div class="col-md-6">
                                    <input id="title" type="text" class="form-control" name="title" value="{{ $category->title }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="image" class="col-md-4 control-label">Image</label>

                                <div class="col-md-6">
                                    <input id="image" type="file" class="form-control" name="image" value="{{ $category->image }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="created_by" class="col-md-4 control-label">Created By</label>

                                <div class="col-md-6">
                                    <input id="created_by" type="text" class="form-control" name="created_by" value="{{ $category->created_by }}" >
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="updated_by" class="col-md-4 control-label">Updated By</label>

                                <div class="col-md-6">
                                    <input id="updated_by" type="text" class="form-control" name="updated_by" value="{{ $category->updated_by }}" >
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">

                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('category.create') }}" class=" btn btn-danger">Create</a>
                                    <a href="{{ route('category.index') }}" class=" btn btn-danger">Category</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

        </div>
    </div>
@endsection

resources/views/category/index.blade.php
@extends('layouts/mogo')

@section('main_content')
    <div class="panel-heading">
        <h5 style="text-align: center">
            Category Lists
            <a href="{{ route('category.create') }}" class=" btn btn-danger pull-right"> Add New Category</a>

        </h5>
        <div style="background:#00b38f; color: #ffffff; width: 600px;text-align: center; font-size: 20px;">{{ session('message') }}</div>
    </div>
    <table id="example1" class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>S.No</th>
            <th>Title</th>
            <th>Image</th>
            <th>Created_by</th>
            <th>Updated_by</th>
            <th>Action</th>

        </tr>
        </thead>
        <tbody>

        @foreach( $categories as $category )


            <tr>
                <td>{{ $loop->index + 1}}</td>
                <td>{{ $category-> title }}</td>
                <td><img style="height: 100px; width: 100px" src="{{asset('uploads/category/'.$category->image)}}"></td>
                <td>{{ $category-> created_by }}</td>
                <td>  {{ $category-> updated_by }}</td>
                <td> <a href="{{ route('category.show',$category->id) }}" class=" btn btn-info"><span class=" glyphicon glyphicon-eye-open"></span></a>
                 <a href="{{ route('category.view') }}" class=" btn btn-info"><span class=" glyphicon glyphicon-eye-open"></span></a>

                    <a href="{{ route('category.edit',$category->id) }}" class=" btn btn-info"><span class="glyphicon glyphicon-edit"></span></a>
                    <form id="delete-form-{{ $category->id }}" method="POST" action="{{ route('category.destroy',$category->id) }}" style="display: none">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                    </form>
                    <a href="" onclick="
                            if(confirm('Are you sure, You went to delete this?'))

                            {
                            event.preventDefault();
                            document.getElementById('delete-form-{{ $category->id }}').submit();
                            }
                            else{
                            event.preventDefault();
                            }
                            " class=" btn btn-info"><span class="glyphicon glyphicon-trash"></span></a>

                </td>
            </tr>
        @endforeach

        </tbody>
        <tfoot>
        <tr>
            <th>S.No</th>
            <th>Title</th>
            <th>Image</th>
            <th>Created_by</th>
            <th>Updated_by</th>
            <th>Action</th>




        </tr>
        </tfoot>
    </table>


@endsection

resources/views/category/view.blade.php
@extends('layouts/mogo')

@section('main_content')


    <main>

        <div class="tt-layout tt-sticky-block__parent ">
            <div class="tt-layout__content">
                <div class="container">
                    <div class="tt-listing-page">
                        @include('include/breadcrumbs')
                        <div class="tt-listing-page__category-name"><h3>Shop Now Category</h3></div>
                        <div class="tt-listing-page__view-options tt-vw-opt">
                            <div class="row">
                                <div class="col-xl-6 col-lg-5 col-md-5 col-xs-12">
                                    <div class="tt-vw-opt__sort">
                                        <span>Sort:</span>
                                        <label class="tt-select">
                                            <select class="form-control">
                                                <option>Default</option>
                                                <option>Default #2</option>
                                                <option>Default #3</option>
                                            </select>
                                        </label>
                                    </div>
                                    <div class="tt-vw-opt__direction">
                                        <a href="#" class="active"><i class="icon-down"></i></a>
                                        <a href="#"><i class="icon-up"></i></a>
                                    </div>
                                </div>
                                <div class="col-xl-3 col-lg-3 col-md-5 col-xs-8">
                                    <div class="tt-vw-opt__info">
                                        <span>Showing 1–9 of 23 results</span>
                                    </div>
                                </div>
                                <div class="col-xl-3 col-lg-4 col-md-2 col-xs-4">
                                    <div class="tt-vw-opt__length">
                                        <span>Show:</span>
                                        <label class="tt-select">
                                            <select class="form-control">
                                                <option>12</option>
                                                <option>9</option>
                                                <option>6</option>
                                            </select>
                                        </label>
                                    </div>
                                    <div class="tt-vw-opt__grid">
                                        <div class="tt-product-btn-vw" data-control=".tt-product-view">
                                            <label>
                                                <input type="radio" name="product-btn-vw" checked>
                                                <i class="icon-th-large"></i>
                                                <i class="icon-check-empty"></i>
                                            </label>
                                            <label>
                                                <input type="radio" name="product-btn-vw"
                                                       data-view-class="tt-product-view--list">
                                                <i class="icon-th"></i>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tt-listing-page__products tt-layout__mobile-full">

                            <div class="tt-product-view row">
                                @foreach( $categories as $category )
                                <div class="col-sm-6 col-xl-4 col-xxl-3">

                                    <div class="tt-product tt-product__view-overlay ttg-text-animation-parent">

                                        <div class="tt-product__image">

                                                <img style="height: 400px; width: 500px" src="{{asset('uploads/category/'.$category->image)}}" data-srcset= "{{asset('uploads/category/'.$category->image)}}"
                                                     data-retina="{{asset('uploads/category/'.$category->image)}}"
                                                     alt="Elegant and fresh. A most attractive mobile power supply.">

                                            <div class="tt-product__labels">
                                                <span class="tt-label__new">New</span>
                                                <span class="tt-label__hot">Hot</span>

                                                <span class="tt-label__sale">Sale</span>
                                                <span class="tt-label__discount">${{  $category->price}}</span>



                                                <div> @if ($category->qty >=1)
                                                        <span class="tt-label__in-stock">In Stock</span>

                                                    @else
                                                        <span class="tt-label__out-stock">Out Stock</span>
                                                    @endif
                                                   </div>
                                            </div>
                                        </div>


                                        <div class="tt-product__hover tt-product__clr-clk-transp">
                                            <div class="tt-product__content">
                                                <h3>
                                            <span class="ttg-text-animation--emersion">
                                                <a href="listing-with-custom-html-block.html">{{  $category->title}}</a>
                                            </span>
                                                </h3>
                                                <p>
                                            <span class="ttg-text-animation--emersion">
                                                <a href="product-simple-variant-1.html">{{  $product->description}}</a>
                                            </span>
                                                </p>
                                                <p class="tt-product__description">{{  $product->description}}</p>
                                                <div class="ttg-text-animation--emersion">
                                            <span class="tt-product__price">
                                                <span class="tt-price tt-price--sale">
                                                    <span>${{  $product->price}}</span>

                                                </span>
                                            </span>
                                                </div>


                                                <div class="ttg-text-animation--emersion">
                                                    <div class="tt-product__buttons">

                                                        <form action="{{ route('cart.store') }}" method="POST">
                                                            {{ csrf_field() }}

                                                            <input type="hidden" name="qty" class="form-control" value="1" value="{{$product->qty}} ">
                                                            <input type="hidden" name="product_id" class="form-control" value="{{ $product->id}}">
                                                            <input type="hidden" name="session_id" class="form-control" value="{{ $id }}">
                                                            <input type="hidden" name="price" class="form-control" value="{{ $product->price}}">

                                                            <a href="{{route('cart.index')}}" >
                                                                <button type="submit" class="tt-btn colorize-btn5  tt-btn__state--active">
                                                                    <i class="icon-shop24"></i>
                                                                    <spam></spam>

                                                                </button>
                                                            </a>

                                                            <a href="{{ route('product.detail',$product->id) }}" class="tt-btn colorize-btn4">
                                                                <i class="icon-eye"></i>
                                                            </a>
                                                        </form>

                                                        <a href="#" class="tt-btn colorize-btn4 tt-product__buttons_like tt-btn__state--active">
                                                            <i class="icon-heart-empty-2"></i>
                                                        </a>
                                                        <a href="#" class="tt-btn colorize-btn4 tt-product__buttons_compare tt-btn__state--active">
                                                            <i class="icon-untitled-1"></i>
                                                        </a>
                                                        <a href="{{ route('product.detail',$product->id) }}" class="tt-btn colorize-btn4">
                                                            <i class="icon-eye"></i>
                                                        </a>

                                                    </div>
                                                </div>
                                                <div class="ttg-text-animation--emersion">

                                                    <span  style="color: darkgreen">{{$category->created_at}}</span>

                                                        <div class="tt-product__countdown" data-date=" {{$product->created_at}}" data-zone="Europe/Madrid">

                                                        </div>




                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                @endforeach
                            </div>
                        </div>
                        {{ $category->links() }}
                    </div>
                </div>
            </div>
        </div>

        <div class="tt-add-to-cart" data-active="true">
            <i class="icon-check"></i>
            <p>Added to Cart Successfully!</p>
            <a href="#" class="btn"><i class="icon-shop24"></i>View Cart</a>
        </div>

        <div class="tt-newsletter-popup" data-active="true">
            <div class="tt-newsletter-popup__text-01">
                <span>15</span>
            <span>
            <span>%</span>
            <span>off</span>
        </span>
            </div>
            <div class="tt-newsletter-popup__text-02"><p>Your Next Purchase When You Sign Up.</p></div>
            <p>By signing up, you accept the terms & Privacy Policy.</p>
            <div class="ttg-mb--30">
                <form action="#" class="tt-newsletter tt-newsletter--style-02">
                    <input type="email" name="email" class="form-control" placeholder="Enter please your e-mail">
                    <button type="submit" class="btn">
                        <i class="tt-newsletter__text-wait"></i>
                        <span class="tt-newsletter__text-default">Subscribe!</span>
                        <span class="tt-newsletter__text-error"><i class="icon-exclamation"></i>Please provide a valid email address!</span>
                        <span class="tt-newsletter__text-complete"><i class="icon-ok"></i>Check your inbox!</span>
                    </button>
                </form>
            </div>
            <div class="tt-newsletter-popup__social">
                <div class="tt-social-icons tt-social-icons--style-03">
                    <a href="#" class="tt-btn">
                        <i class="icon-facebook"></i>
                    </a>
                    <a href="#" class="tt-btn">
                        <i class="icon-twitter"></i>
                    </a>
                    <a href="#" class="tt-btn">
                        <i class="icon-gplus"></i>
                    </a>
                    <a href="#" class="tt-btn">
                        <i class="icon-instagram-1"></i>
                    </a>
                    <a href="#" class="tt-btn">
                        <i class="icon-youtube-play"></i>
                    </a>
                </div>
            </div>
            <label class="tt-newsletter-popup__show_popup tt-checkbox">
                <input type="checkbox" name="show-nawslatter">
                <span></span>
                Don't show this popup again
            </label>
        </div>
    </main>




@endsection